name: dorm_buddy
description: "A Dorm Buddy application."

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  image_picker: ^1.1.2
  #Change 5
  #firebase_core: ^3.13.1
  #firebase_auth: ^4.11.1  # For user authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.15.0
  flutter_bloc: ^9.1.1
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/images/bedroom.jpg
    - lib/assets/images/property_outside.jpg
    - lib/assets/images/room.jpg