// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6DDn6jjAULlnvjLjczHLfBJSnK6iPyo',
    appId: '1:144123476622:web:b7c844e6ba7deff6f0a7df',
    messagingSenderId: '144123476622',
    projectId: 'dormbuddy-859e9',
    authDomain: 'dormbuddy-859e9.firebaseapp.com',
    storageBucket: 'dormbuddy-859e9.firebasestorage.app',
    measurementId: 'G-XHB59KM00L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJ87wO9l6rgqqpqJ6HX530gYp7crqNFw',
    appId: '1:144123476622:android:fdc8745eba27cd2af0a7df',
    messagingSenderId: '144123476622',
    projectId: 'dormbuddy-859e9',
    storageBucket: 'dormbuddy-859e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9y_sn-hAGrJh65jM0-aOhUxMzSChajU',
    appId: '1:144123476622:ios:d9bddbfa4d651e2bf0a7df',
    messagingSenderId: '144123476622',
    projectId: 'dormbuddy-859e9',
    storageBucket: 'dormbuddy-859e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9y_sn-hAGrJh65jM0-aOhUxMzSChajU',
    appId: '1:144123476622:ios:d9bddbfa4d651e2bf0a7df',
    messagingSenderId: '144123476622',
    projectId: 'dormbuddy-859e9',
    storageBucket: 'dormbuddy-859e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6DDn6jjAULlnvjLjczHLfBJSnK6iPyo',
    appId: '1:144123476622:web:e632bdf38f572328f0a7df',
    messagingSenderId: '144123476622',
    projectId: 'dormbuddy-859e9',
    authDomain: 'dormbuddy-859e9.firebaseapp.com',
    storageBucket: 'dormbuddy-859e9.firebasestorage.app',
    measurementId: 'G-40QD6709XC',
  );
}
