import 'package:dorm_buddy/pages/dashboard/landlord/edit_profile_landlord.dart';
import 'package:dorm_buddy/pages/dashboard/landlord/property_details.dart';
import 'package:dorm_buddy/pages/dashboard/student/edit_student_profile.dart';
import 'package:firebase_core/firebase_core.dart'; //idk why this is needed but it is lol
import 'firebase_options.dart'; // Generated by flutterfire CLI
import 'package:flutter/material.dart';
import 'pages/login_page.dart';
import 'pages/register/register_student_page.dart';
import 'pages/register/register_landlord_page.dart';
import 'pages/dashboard/student_dashboard.dart';
import 'pages/dashboard/landlord_dashboard.dart';
import 'pages/forgot_password_page.dart';

import 'pages/dashboard/student/profile.dart';
import 'pages/dashboard/landlord/add_dorm.dart';
//import 'pages/dashboard/landlord/landlord_chat.dart';
//import 'pages/dashboard/landlord/landlord_profile.dart';
import 'pages/dashboard/landlord/delete_dorm.dart';



//Change #6
void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensures Flutter binding
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    runApp(const DormBuddyApp());
  } catch (e, stackTrace) {
    print("Firebase init failed: $e");
    print(stackTrace);
  }
}

class DormBuddyApp extends StatelessWidget {
  const DormBuddyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false, // Disable debug banner
      title: 'DormBuddy',
      theme: ThemeData(
        primarySwatch: Colors.red,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF800000),
          secondary: const Color(0xFFA52A2A),
        ),
      ),
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/register/student': (context) => const RegisterStudentPage(),
        '/register/landlord': (context) => const RegisterLandlordPage(),
        '/student-dashboard': (context) => const StudentDashboard(),
        '/landlord-dashboard': (context) => const LandlordDashboard(),
        '/forgot': (context) => const ForgotPasswordPage(),

        '/search': (context) => const StudentDashboard(),//temporary
        '/profile': (context) => const StudentProfilePage(),

      //  '/landlord_dashboard': (context) => const LandlordDashboard(),
        '/property_details': (context) => const PropertyDetailsPage(),
        '/add_dorm': (context) => const AddDormPage(),
      //  '/landlord_chat': (context) => LandlordChatPage(),
      //  '/landlord_profile': (context) => const LandlordProfilePage(),
        '/delete_property': (context) => const DeleteDormPage(),
        'edit_landlord': (context) => const EditLandlordProfilePage(),
        'edit_student': (context) => const EditStudentProfilePage(), 

        

      },
    );
  }
}
